### ISSUE TITLE
Teleport direction is always positive

### ISSUE THREAD

**Issue by rusty-snake** [JustinLaw64/meseport#1]
Teleport in negative directions is broken.

```
MMG : teleport to +200 (should: +200)
GMM : teleport to +200 (should: -200)
MGM : teleport to +100 (should: 0)

M: Mese
G: Gold
```

**Comment by JustinLaw64** [comment]
Sorry for the delayed response.

I've fixed the issue by adding ` * polarity` to the power calculation so that the polarity variable applies as originally intended, among other changes, in commit 51287bb.

https://github.com/JustinLaw64/meseport/blob/51287bb5eef8ca8c2794e67ec54f5a3f8e1283a7/init.lua#L24

Thanks for notifying me of this!

**Comment by rusty-snake** [comment]
Can you push this to contentDB, thanks.

**Comment by JustinLaw64** [comment]
I've just pushed the update to ContentDB.

https://content.minetest.net/packages/ForbiddenJ/meseport/
